import { tool, type Plugin } from "@opencode-ai/plugin"
import { existsSync } from "node:fs"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"

const LEARNINGS_DIR = ".opencode/learnings"
const EXPORTS_DIR = `${LEARNINGS_DIR}/exports`
const ITEMS_DIR = `${LEARNINGS_DIR}/items`
const INDEX_FILE = `${LEARNINGS_DIR}/INDEX.md`
const STATS_FILE = `${LEARNINGS_DIR}/.stats.json`
const MAX_TOOL_OUTPUT_CHARS = 1200
const DEFAULT_INDEX_CONTENT = [
  "# Project Learnings Index",
  "",
  "> This file is loaded automatically via `opencode.jsonc` instructions.",
  "> Read a detailed learning file only when the current task clearly matches it.",
  "",
  "<!-- Auto-generated by /learn. Manual edits may be overwritten. -->",
  "",
  "_No learnings yet. Run `/learn` after solving a non-obvious problem to capture one._",
  "",
].join("\n")

type LearningStats = Record<
  string,
  {
    hits: number
    first_used: string | null
    last_used: string | null
  }
>

function toAbsoluteProjectPath(directory: string, filePath: string) {
  return path.isAbsolute(filePath) ? filePath : path.resolve(directory, filePath)
}

function toProjectRelativePath(directory: string, filePath: string) {
  return path.relative(directory, toAbsoluteProjectPath(directory, filePath)).split(path.sep).join("/")
}

function getTrackedLearningSlug(directory: string, filePath: string | undefined) {
  if (!filePath) return null

  const relativePath = toProjectRelativePath(directory, filePath)
  if (!relativePath.startsWith(`${ITEMS_DIR}/`)) return null
  if (!relativePath.endsWith(".md")) return null

  const baseName = path.basename(relativePath)
  if (baseName.startsWith(".")) return null

  return baseName.replace(/\.md$/, "")
}

function truncate(text: string, max = MAX_TOOL_OUTPUT_CHARS) {
  if (text.length <= max) return text
  return `${text.slice(0, max).trimEnd()}\n[output truncated]`
}

function redactSensitiveText(text: string) {
  return text
    .replace(/Authorization:\s*[^\n]+/gi, "Authorization: [redacted]")
    .replace(/\b(?:ghp_|github_pat_|sk-)[A-Za-z0-9_-]+\b/g, "[redacted]")
}

function summarizeToolOutput(text: string) {
  const trimmed = String(text ?? "").trim()
  if (!trimmed) return "[no output]"
  return truncate(redactSensitiveText(trimmed))
}

function formatTimestamp(value: number | undefined) {
  if (!value) return "unknown"
  return new Date(value).toISOString()
}

function formatToolPart(part: any) {
  const state = part.state

  if (state.status === "completed") {
    return [
      `### Tool: ${part.tool}`,
      `Status: completed`,
      `Input: ${JSON.stringify(state.input)}`,
      `Output: ${summarizeToolOutput(state.output)}`,
    ].join("\n")
  }

  if (state.status === "error") {
    return [
      `### Tool: ${part.tool}`,
      `Status: error`,
      `Input: ${JSON.stringify(state.input)}`,
      `Error: ${summarizeToolOutput(state.error)}`,
    ].join("\n")
  }

  if (state.status === "running") {
    return [
      `### Tool: ${part.tool}`,
      `Status: running`,
      `Input: ${JSON.stringify(state.input)}`,
    ].join("\n")
  }

  return [
    `### Tool: ${part.tool}`,
    `Status: pending`,
    `Input: ${JSON.stringify(state.input)}`,
  ].join("\n")
}

function formatPart(part: any): string | null {
  if (part.type === "text") {
    const text = String(part.text ?? "").trim()
    return text || null
  }

  if (part.type === "tool") return formatToolPart(part)

  if (part.type === "subtask") {
    return [
      `### Subtask: ${part.agent}`,
      `Description: ${part.description}`,
      part.command ? `Command: ${part.command}` : null,
    ]
      .filter(Boolean)
      .join("\n")
  }

  if (part.type === "agent") {
    return `### Agent\n${part.name}`
  }

  return null
}

function formatMessage(entry: any) {
  const role = entry.info.role === "assistant" ? "Assistant" : "User"
  const renderedParts = entry.parts.map(formatPart).filter(Boolean)

  return [
    `## ${role}`,
    `- Message ID: ${entry.info.id}`,
    `- Created: ${formatTimestamp(entry.info.time?.created)}`,
    "",
    renderedParts.length > 0 ? renderedParts.join("\n\n") : "[no exported parts]",
  ].join("\n")
}

async function ensureLearningDirs(directory: string) {
  await mkdir(path.join(directory, EXPORTS_DIR), { recursive: true })
  await mkdir(path.join(directory, ITEMS_DIR), { recursive: true })

  const indexPath = path.join(directory, INDEX_FILE)
  if (!existsSync(indexPath)) {
    await writeFile(indexPath, DEFAULT_INDEX_CONTENT, "utf-8")
  }
}

async function resolveSessionID(client: any, directory: string, sessionID: string) {
  if (sessionID !== "current") return sessionID

  const sessionsResult = await client.session.list(
    {
      query: { directory },
      throwOnError: false,
    },
  )

  if (sessionsResult.error || !sessionsResult.data?.length) return sessionID

  const latestSession = [...sessionsResult.data].sort((left: any, right: any) => {
    const leftUpdatedAt = left.time?.updated ?? left.time?.created ?? 0
    const rightUpdatedAt = right.time?.updated ?? right.time?.created ?? 0
    return rightUpdatedAt - leftUpdatedAt
  })[0]

  return latestSession?.parentID ?? latestSession?.id ?? sessionID
}

async function loadStats(directory: string): Promise<LearningStats> {
  const absolutePath = path.join(directory, STATS_FILE)
  if (!existsSync(absolutePath)) return {}

  try {
    const raw = await readFile(absolutePath, "utf-8")
    return JSON.parse(raw) as LearningStats
  } catch {
    return {}
  }
}

async function saveStats(directory: string, stats: LearningStats) {
  await mkdir(path.join(directory, LEARNINGS_DIR), { recursive: true })
  await writeFile(path.join(directory, STATS_FILE), `${JSON.stringify(stats, null, 2)}\n`, "utf-8")
}

async function exportSessionMarkdown(client: any, directory: string, sessionID: string) {
  const sessionResult = await client.session.get(
    {
      path: { id: sessionID },
      query: { directory },
      throwOnError: false,
    },
  )

  if (sessionResult.error || !sessionResult.data) {
    throw new Error(`Could not load session ${sessionID}`)
  }

  const messagesResult = await client.session.messages(
    {
      path: { id: sessionID },
      query: { directory, limit: 500 },
      throwOnError: false,
    },
  )

  if (messagesResult.error || !messagesResult.data) {
    throw new Error(`Could not load messages for session ${sessionID}`)
  }

  const exportedAt = new Date().toISOString()
  const exportDate = exportedAt.slice(0, 10)
  const relativePath = `${EXPORTS_DIR}/${exportDate}_${sessionID}.md`
  const absolutePath = path.join(directory, relativePath)

  const markdown = [
    "# Session Export",
    "",
    `- Session ID: ${sessionID}`,
    `- Title: ${sessionResult.data.title || "Untitled"}`,
    `- Exported At: ${exportedAt}`,
    `- Export Type: current-effective-session-state`,
    "",
    "## Messages",
    "",
    ...messagesResult.data.map(formatMessage),
    "",
  ].join("\n")

  await writeFile(absolutePath, markdown, "utf-8")

  return {
    relativePath,
    messageCount: messagesResult.data.length,
  }
}

export const LearningSystem: Plugin = async ({ client, directory }) => {
  return {
    tool: {
      learning_export_session: tool({
        description: "Export the current session to a markdown file under .opencode/learnings/exports/",
        args: {
          sessionID: tool.schema.string().optional().describe("Session ID to export. Defaults to the current session."),
        },
        async execute(args, context) {
          const sessionID = await resolveSessionID(
            client,
            context.directory,
            args.sessionID ?? context.sessionID,
          )

          await ensureLearningDirs(context.directory)
          const exported = await exportSessionMarkdown(client, context.directory, sessionID)

          return `Saved session export to ${exported.relativePath} (${exported.messageCount} messages)`
        },
      }),
    },
    "tool.execute.after": async (input) => {
      if (input.tool !== "read") return

      const slug = getTrackedLearningSlug(directory, input.args?.filePath ?? input.args?.path)
      if (!slug) return

      const stats = await loadStats(directory)
      const now = new Date().toISOString()

      stats[slug] = stats[slug] ?? {
        hits: 0,
        first_used: null,
        last_used: null,
      }

      stats[slug].hits += 1
      stats[slug].last_used = now
      stats[slug].first_used ??= now

      await saveStats(directory, stats)
    },
  }
}
